### ISSUE TITLE
Refactor modules and classes to not be an EventEmitter

### ISSUE THREAD

**Issue by dglol** [mozilla/memchaser#103]
We should centralize events just like we centralized the preferences. It doesn't make sense for every module to emit its own events. By centralizing events, I mean to have only two Event emitters: EventEmitter and self.

This will enhance maintainability and it will reduce the overhead of the unnecessary mixin. Also, when EventEmitter is deprecated, it will be easier to swap out EventEmitter.

**Comment by xabolcs** [comment]
`EventEmitter` is gone near Firefox 40, see Travis build [64179805][1]!


[1]: https://travis-ci.org/mozilla/memchaser/builds/64179805

**Comment by xabolcs** [comment]
Bug [1158534][1] - End Traits ... landed as [b1a9b43c430c][2].

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1158534 "End Traits"
[2]: https://github.com/mozilla/addon-sdk/commit/b1a9b43c430c58884957afa3100e55bcfa7ebddf

**Comment by whimboo** [comment]
To be able to properly test the upcoming front-end changes we should first fix the back-end modules. So getting rid of emitters and using the new proposed technology sounds like the first step to do.

**Comment by xabolcs** [comment]
Sure!

**Comment by xabolcs** [comment]
@dglol, @whimboo 
PR #217 is for the `EventEmitter` part.

The original description (centralize message emitters) is still valid?

**Comment by whimboo** [comment]
Not sure if it is still valid. Lets get the first part in and we can see. Btw. David is not with us since 2012.

**Comment by whimboo** [comment]
PR #217 has been merged! Hurray for a working memchaser addon again. Thanks @xabolcs.
