### ISSUE TITLE
Upgrade from widget to toolbar api to support Australis

### ISSUE THREAD

**Issue by whimboo** [mozilla/memchaser#183]
As what I got today from the Addon SDK guys is that we have to upgrade memchaser so we really support the new toolbars. Widgets are deprecated and will be removed at some time. So we need support for the toolbar API but also should leave fallback code for widget in the tool if possible.

**Comment by whimboo** [comment]
Sad news here... given that amount of work and that I will be away for some weeks soon, I won't be able to do any work on this issue before May. While I'm away maybe @KWierso can at least review a PR given that he has great knowledge about the Add-on SDK.

**Comment by xabolcs** [comment]
> Sad news here...

Acknowledged.

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

**Comment by xabolcs** [comment]
From Issue #213.
> I should have time for discussion and reviews if requested.

Please rethink / redesign the GUI of MemChaser!
I could have time if you clearly specify what do you want for MemChaser!

As you could see there is no real successor of `Widget` module. I had to apply lot of workaround to mimic it with `ui/toolbar` module. IMHO `ui/toolbar` isn't for context menus and tooltips. Sorry.

See [`ui/toolbar`][1] documentation!

[1]: https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_toolbar

**Comment by whimboo** [comment]
That is great to hear @xabolcs! 

What we would need here is a panel-only version without any fallback code to widget. So a toolbar is definitely the way to go. Including there we would most likely have to use a frame to an HTML file, similar to the example in the referenced toolbar documentation. We should be able to keep the UI identical to what we currently have. I assume that our backend modules will stay the same and we only have to communicate with them via postMessage? I would do that as the first step before caring about the popup and its actions. What do you think?

**Comment by xabolcs** [comment]
> What we would need here is a panel-only version without any fallback code to widget. So a toolbar is definitely the way to go.

Yes, no fallback code here. Yes, toolbar is the way to go here. For button way there is Issue #176, as an alternate GUI.

> Including there we would most likely have to use a frame to an HTML file, similar to the example in the referenced toolbar documentation.

Yeah, we could put frames and buttons on to toolbar, nothing else.

> We should be able to keep the UI identical to what we currently have.

I'm on the opposite side. Design a whole new UI, for toolbar in mind. If needed, name it 1.0!
The old UI isn't compatible with the new `toolbar` module.
Take all the functionalities, prioritize them, put the TOP N on the toolbar and do something with the others.
If the change is major, let it v1.0, if minor let it v0.7.

>  I assume that our backend modules will stay the same and we only have to communicate with them via postMessage?

Most coding work would happen in the frame's source and in `main.js`, others would be untouched.

>  I would do that as the first step before caring about the popup and its actions. What do you think?

You missed out the tooltips. ;-)

As I wrote above, imagine that you are making a new SDK addon with `ui/toolbar` module from some already written modules with logging, gc and memory reporting features.
The new addon have some item on it's nice to have list, e.g. triggering memory related events, providing nice descriptions on the reported items, etc.

**Comment by whimboo** [comment]
> Yes, no fallback code here. Yes, toolbar is the way to go here. For
> button way there is Issue #176
> <https://github.com/mozilla/memchaser/issues/176>, as an alternate GUI.

This can definitely wait. First we should restore the behaviour we had
before with the widget code, which allowed an easy way to always have
the values visible.

>     We should be able to keep the UI identical to what we currently have.
> 
> I'm on the opposite side. Design a whole new UI, for toolbar in mind. If
> needed, name it 1.0!

I don't say that we should take the implementation but the layout in
terms of what is displayed. The current code might be a bit nasty so a
refactoring would always be good.

> The old UI isn't compatible with the new |toolbar| module.
> Take all the functionalities, prioritize them, put the TOP N on the
> toolbar and do something with the others.
> If the change is major, let it v1.0, if minor let it v0.7.

Those are not that many features which would require a largish
prioritization. But first should definitely come the memory usage, if
that is the feedback you would like to hear. :)

>     I assume that our backend modules will stay the same and we only
>     have to communicate with them via postMessage?
> 
> Most coding work would happen in the frame's source and in |main.js|,
> others would be untouched.

Great to hear.

>     I would do that as the first step before caring about the popup and
>     its actions. What do you think?
> 
> You missed out the tooltips. ;-)

Those are kind of popup. :) But yes, those would be nice too.

> As I wrote above, imagine that you are making a new SDK addon with
> |ui/toolbar| module from some already written modules with logging, gc
> and memory reporting features.
> The new addon have some item on it's nice to have list, e.g. triggering
> memory related events, providing nice descriptions on the reported
> items, etc.

Sounds fine with me. When you start implementing the ideas maybe lets do
it in smaller steps and have review/feedback cycles more often? As
smaller the code to review as faster I can do it.

Thanks a lot that you really wanna take it!

**Comment by xabolcs** [comment]
> Sounds fine with me. When you start implementing the ideas maybe lets do it in smaller steps and have review/feedback cycles more often? As smaller the code to review as faster I can do it.

First of all, let land the logging PR. :)

I'll start soon the coding, and open a PR for it ... not to review, but to see how I imagine all this.
Sure, I'll take small steps.

**Comment by xabolcs** [comment]
PR #220 is merged.
