### ISSUE TITLE
Improve Travis-CI to run tests with every supported Firefox release

### ISSUE THREAD

**Issue by xabolcs** [mozilla/memchaser#191]
See subject!

**Comment by whimboo** [comment]
To make that happen we could use mozdownload to actually download the firefox build from our FTP server. We do a similar thing in https://github.com/mozilla/firefox-ui-tests/blob/master/.travis.yml#L27 now.

**Comment by xabolcs** [comment]
> We do a similar thing in https://github.com/mozilla/firefox-ui-tests/blob/master/.travis.yml#L27 now.

Whoa! Thanks for the tip!
Will give it a try on this week.

**Comment by xabolcs** [comment]
[Here][1] is a nice log about how `mozdownload` could work.

[1]: https://travis-ci.org/mozilla/memchaser/builds/47163670

**Comment by whimboo** [comment]
Yeah that looks great. That way we could build up a matrix with different versions of Firefox.

**Comment by xabolcs** [comment]
Thanks!

Now let's specify what to do here.
Should I really download and test with latest ESR, latest beta and latest daily release?

I'm done with `mozdownload`, and I don't know the next step.

**Comment by whimboo** [comment]
There is a way to setup a matrix for tests. We did this with Python 2.6 and 2.7 on the [mozdownload repository](https://github.com/mozilla/mozdownload/blob/master/.travis.yml). Not sure if something like that is possible with your own versions.

**Comment by xabolcs** [comment]
Yeah, build matrix is supported. What versions of Firefox should I test? $subject would be enough: `beta` and `ESR`?

**Comment by whimboo** [comment]
Best would be each supported version: nightly, aurora, beta, release, latest esr. Only that way we can make sure to not regress something or getting regressed by a change in Firefox.

**Comment by xabolcs** [comment]
Fixed by the commit 4a1cada77f7718b4cd15cae832d7824bc8d5fc50, above.
