### ISSUE TITLE
Add ANT target which posts the built xpi to Extension Auto-Installer

### ISSUE THREAD

**Issue by xabolcs** [mozilla/memchaser#205]
When I'm developing MemChaser I install it with [Extension Auto-Installer][1] into the target Application.
```
$ ant package
$ XPI=`ls -1 xpi/*.xpi`; wget --post-file="$XPI" http://localhost:8888/ 
```

It would be nice if there would be an ant target which contains these two step above.

[1]: https://addons.mozilla.org/addon/358040/

**Comment by whimboo** [comment]
Good to hear that `ant run` works for you. So yes, I would prefer to close it as wontfix then. Thanks for your feedback - even I'm very late with my reply here.
