### ISSUE TITLE
test-logger.js has unstable results

### ISSUE THREAD

**Issue by xabolcs** [mozilla/memchaser#208]
For example see Travis CI builds for PR #206:
 * build [49405962][1]
 * build [49570673][2]
 * local build in the [pull request][3]

[1]: https://travis-ci.org/mozilla/memchaser/builds/49405962
[2]: https://travis-ci.org/mozilla/memchaser/builds/49570673
[3]: https://github.com/mozilla/memchaser/pull/206#issuecomment-73163409

**Comment by xabolcs** [comment]
Nice! Latest [build][1] has full of `test-logger.js` error.

[1]: https://travis-ci.org/mozilla/memchaser/jobs/50209008

**Comment by xabolcs** [comment]
What a surprise! `Logger._writeAsync` isn't a FIFO. See [pastebin][1]!


[1]: http://pastebin.mozilla.org/8678657 "writeAsyinc is out of sequence at 71"

**Comment by xabolcs** [comment]
I think rewriting `logger.js` and  `test-logger.js` to use promises (and [`sdk/io/text-streams`][1] or [`OS.File`][2]) is the way here.

[1]: https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/io_text-streams
[2]: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.File_for_the_main_thread

**Comment by xabolcs** [comment]
Thankfully `OS.File`'s `write` use FIFO!

**Comment by xabolcs** [comment]
So I have an `OS.File` based fix, for ESR31 also! :)

**Comment by whimboo** [comment]
Sounds good. Does it mean we need a fix in the code of memchaser or only this test?

**Comment by xabolcs** [comment]
I modified `Logger.prototype._writeAsync`, and added a new test `test_high_speed_logging`.

I propose a change to `build.xml` (and for `travis.yml`).
It would be nice if Travis CI would have detailed test output: it would be nice to change `build.xml`'s `test` target to use `--verbose` parameter for `cfx` if runs under Travis CI.
A new build parameter (like `-Dbinary` is now) would be nice. It would help for local testing too.
Thoughts?

**Comment by whimboo** [comment]
I would always enable verbose logging for `cfx test`, but we could make it opt-in for `cfx run` and similar commands.

**Comment by xabolcs** [comment]
> I would ...

Filed as #209. Thanks for accepting.

**Comment by xabolcs** [comment]
> So I have an OS.File based fix, for ESR31 also! :)

Now it works with 24.8.1 too. :)

**Comment by xabolcs** [comment]
Fixed by commit 45fd7accf66835762f1ef92470e9a5f1e8370980.
