### ISSUE TITLE
Log files are created with execute permissions

### ISSUE THREAD

**Issue by atrigent** [mozilla/memchaser#215]
https://github.com/mozilla/memchaser/commit/eeae109d679be115cdacfcfb595b26bd4354e037#diff-df0c5921236e8e25daf27ddd7b755dc6R15

**Comment by xabolcs** [comment]
Only group and world have execute permissions, the owner doesn't.

What kind of permissions would you like to see?

**Comment by atrigent** [comment]
Having any execute permissions at all on this file doesn't make any sense, considering that it's json. And the 0655 file mode doesn't make much sense in general, for the reason that you stated. The mode for this file should probably be 0644 or 0600.

**Comment by xabolcs** [comment]
PR #211 has related [changes][1]. Let's see if that fixes it.


[1]: https://github.com/mozilla/memchaser/pull/211/files#diff-df0c5921236e8e25daf27ddd7b755dc6L12

**Comment by atrigent** [comment]
The documentation for OS.File.open()[1] states that the default for the creation mode (options.unixMode, which you are not overriding, obviously) is 0600, so yes it does seem like that PR would fix this issue.

Thanks.

[1] https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.File_for_the_main_thread#OS.File.open%28%29

**Comment by whimboo** [comment]
I don't see where in `655` the executable bit is set. This is only necessary for the directory. Maybe you mix-up those two constants?

**Comment by xabolcs** [comment]
r=4
w=2
x=1

`7=rwx`, `6=rw-`, `5=r-x`, `4=r--`

Permissions are mostly `644 = rw-, r--, r--` and `755 = rwx, r-x, r-x`.

**Comment by atrigent** [comment]
```
0655 = 110101101
       rw-r-xr-x
```

Notice the "x"es.

**Comment by whimboo** [comment]
Gna, right! Sorry, seems to be too late for me. Lets get this fixed by the already existent PR.

**Comment by whimboo** [comment]
PR #211 has been merged now. So this is fixed now.
