### ISSUE TITLE
Add information to frame if ghost windows are present

### ISSUE THREAD

**Issue by whimboo** [mozilla/memchaser#224]
As it came out of issue #221 it would be useful if memchaser could display if ghost windows are present. about:memory shows it like:

10 (100.0%) -- ghost-windows
├───5 (50.00%) ── http://vodlocker.com/[...] [5]
├───2 (20.00%) ── http://disqus.com/embed/comments/[...] [2]
├───2 (20.00%) ── https://translate.googleusercontent.com/translate_c?[...] [2]
└───1 (10.00%) ── http://watch-series-tv.to/open/cale/[...]

Maybe there is an API we can use to get this information? Without having a look at the code I might wanna ask @amccreight directly. :)

**Comment by xabolcs** [comment]
This is a dupe.
@whimboo do you remember #129? ;)

**Comment by xabolcs** [comment]
Btw could you provide an STR, if you don't mind?
