### ISSUE TITLE
Memchaser stoped showing in the add-on bar

### ISSUE THREAD

**Issue by rayman89** [mozilla/memchaser#232]
Memchaser now shows as a toolbar and i cannot get it to show in the add-on bar/status bar like it used to. I tried going to customize and it's not showing there and I cannot drag the memchaser icon from that toolbar to the add-on bar either. Uninstalling it and installing it again didn't solve it.

**Comment by gitmeister** [comment]
The author indicated that there's no more addon toolbar but i'm using FF40 and I still have Cookie Controller, Xmarks, Live IP & View Source on that addon toolbar so maybe i'm misunderstanding the limitation.

**Comment by rayman89** [comment]
add-ons exist to restore it doesnt it? Where did you see that comment?

**Comment by gitmeister** [comment]
I read the comment on the reviews for Memchaser on the FF plugin site. Actually I *am* using Classic Theme Restorer and I didn't realize that it restores that bar (i disabled it and the addon bar disappeared). So I tried loading an older version of Memchaser to see if that would hook back into the addon bar... but it didn't. Oddly, the other addons I mentioned before still appear fine.

**Comment by buckleyw** [comment]
I'm also seeing this issue as of a few days ago (running the main release branch of Firefox, so around the 39.0.3 release) and have had to hide the MemChaser's toolbar since it is massive, roughly twice the height of the Bookmarks Toolbar. Like gitmeister I use Classic Theme Restorer to retain the Add-on Bar/status bar and despite my best efforts I cannot get the MemChaser toolbar item to move to any location aside from its' own bar, making it effectively useless.

**Comment by xabolcs** [comment]
Hi Users!

Bad news here! The movable toolbar item was removed in Firefox 40. The 0.6 version doesn't work with Firefox 40.

So we was forced to use the new [`ui/toolbar`][1] API from Addon SDK. And - as you can see - it has some limitations compared to the old [`widget`][2] API what provided the toolbar item.

To address your problems an issue was already filed: #230.
In the mean time you could hide the MemChaser toolbar, when you don't need, and show it only when you are interested in the numbers. Not perfect workaround, but it works.

As a last resort you could downgrade to Firefox 39 or below and use version 0.6 with it's movable toolbar item. But please consider the security threats for that old Firefox!


[1]: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/ui#Toolbar
[2]: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/widget

**Comment by whimboo** [comment]
As I wrote in my reply on AMO and what @xabolcs is saying here, we do not have an alternative here at the moment. We were actually happy to have made the timeline for the 0.7 release close to Firefox 40.0. 

If you want to follow further development please subscribe to the issue as pointed out.
