### ISSUE TITLE
Travis CI says "This is not an active repository" - make CI working again

### ISSUE THREAD

**Issue by xabolcs** [mozilla/memchaser#233]
STR:
 - click on the Continuous Integration [icon][1]

[1]: http://travis-ci.org/mozilla/memchaser

**Comment by xabolcs** [comment]
@whimboo, as I wouldn't like to get an admin right for this repository, I assigned you for this issue! :)

You need to follow the steps on [docs.travis-ci.com][1]!

> Once you’re signed in, and we’ve synchronized your repositories from GitHub, go to your profile page and enable Travis CI for the repository you want to build.
>
> >   _Note: You can only enable Travis CI builds for repositories you have admin access to._


[1]: http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

**Comment by whimboo** [comment]
We had the same problem with the firefox-ui-tests repository yesterday. Not sure what actually went on. I will fix it.

**Comment by xabolcs** [comment]
Thanks!

**Comment by whimboo** [comment]
Done
