### ISSUE TITLE
Avoid Fixed width Layout, Prefer em to px as Fallback

### ISSUE THREAD

**Issue by anon-user** [mozilla/memchaser#85]
Memchaser 0.2 uses:
toolbaritem style="min-width: 360px;"
iframe style="width: 360px;"

However, given that I have a smaller font size, this leaves a significant blank space to the left.
For other users, this may cause hidden overflow...

If you *MUST* force the width, try something like '22em;' instead, which will scale with font size.

Better yet, avoid a fixed width layout entirely!

**Comment by xabolcs** [comment]
Wontfix, isn't it?

**Comment by whimboo** [comment]
Jepp, there are no hard-coded width anymore.
